app:
  version: "5.0.0"
  artifacts_dir: "./artifacts"
  cache_dir: ".supercaderno_cache"

models:
  flash: { name: "gemini-flash-latest", temperature: 0.3, safety: "default" }
  pro:   { name: "gemini-pro-latest",   temperature: 0.3, safety: "default" }

limits:
  max_workers_llm: 4
  min_hits_prefilter: 1      # economy eleva para 2
  window_pages: 1            # usado na v5.1
  max_calls: null

prompts:
  extractor: "./prompts/extractor.jinja.md"
  consolidator: "./prompts/consolidator.jinja.md"
  synopsis: "./prompts/synopsis.jinja.md"

text:
  placeholder_vazio: "> ⚠️ Conteúdo não encontrado para este tópico."
